### ISSUE TITLE
mqtt ?

### ISSUE THREAD

**Issue by Masterxv** [hallard/rgb-matrix-crypto-ticker#1]
mqtt': {'host': '192.168.29.60', 'port': 1883, 'topic': 'smartclock/smartclock-40e0/tele/SENSOR', 'username': None, 'password': None}}
ERROR:root:[Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 567, in main
    mqtt_client.connect(config['mqtt']['host'], config['mqtt']['port'])
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 610, in <module>
    main()
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 596, in main
    image=beanaproblem(str(e)+" Line: "+str(e.__traceback__.tb_lineno))
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 233, in beanaproblem
    writewrappedlines(image, "Issue:"+message, y_text=3, fill='red')
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 140, in writewrappedlines
    _place_text(img, line,0, y_text, fontsize,fontstring, fill)
  File "/home/pi/rgb-matrix-crypto-ticker/./cryptoticker.py", line 130, in _place_text
    text_width, _ = font.getsize(text)
AttributeError: 'ImageFont' object has no attribute 'getsize'

**Comment by hallard** [comment]
May be your broker is waiting for authenticated connexion.
